enum AppFeature {
  clientServiceRequest,
  invitation,
  workOrder,
  workReport,
  positions,
  form,
  service,
  profile,
  company,
  employee,
  publicCompanies,
  publicClientServiceRequest,
  senderInvitation,
  receiverInvitation,
}