// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWpghccBe8sxAVLsq5yMv-GnrIQvJ4o0s',
    appId: '1:536307167558:web:d3f45161a4727c28f07547',
    messagingSenderId: '536307167558',
    projectId: 'workorder-team',
    authDomain: 'workorder-team.firebaseapp.com',
    storageBucket: 'workorder-team.firebasestorage.app',
    measurementId: 'G-7W9V93WDW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbDMO7keL3hTlxsfB8d2011NG5fIRcWxQ',
    appId: '1:536307167558:android:64fb0904c9cfb70ff07547',
    messagingSenderId: '536307167558',
    projectId: 'workorder-team',
    storageBucket: 'workorder-team.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK2XVGVOMbREMYQVKlYNpiFnR7eSEtEaI',
    appId: '1:536307167558:ios:11d61a1e150a4393f07547',
    messagingSenderId: '536307167558',
    projectId: 'workorder-team',
    storageBucket: 'workorder-team.firebasestorage.app',
    iosBundleId: 'com.example.workorderCompanyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK2XVGVOMbREMYQVKlYNpiFnR7eSEtEaI',
    appId: '1:536307167558:ios:11d61a1e150a4393f07547',
    messagingSenderId: '536307167558',
    projectId: 'workorder-team',
    storageBucket: 'workorder-team.firebasestorage.app',
    iosBundleId: 'com.example.workorderCompanyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWpghccBe8sxAVLsq5yMv-GnrIQvJ4o0s',
    appId: '1:536307167558:web:865b2211dd801271f07547',
    messagingSenderId: '536307167558',
    projectId: 'workorder-team',
    authDomain: 'workorder-team.firebaseapp.com',
    storageBucket: 'workorder-team.firebasestorage.app',
    measurementId: 'G-9M1N8FRFFY',
  );
}
